### ISSUE TITLE
workaround low resolution in e2e

### ISSUE THREAD

**Issue by jludvice** [redhat-ipaas/ipaas-ui#401]
For instance here, we fill all details and we want to click on button `Next`,
but its' overriden by to nav bar and tests fail with 
```
1) Scenario: Create connection happy path - e2e/connections/connections.feature:16
   Step: And click on the "Next" button - e2e/connections/connections.feature:22
   Step Definition: node_modules/cucumber-tsflow/src/BindingDecorator.ts:163
   Message:
     WebDriverError: unknown error: Element <button _ngcontent-fmj-107="" class="btn btn-primary">...</button> is not clickable at point (1217, 13). Other element would receive the click: <a _ngcontent-fmj-47="" aria-expanded="true" aria-haspopup="true" class="dropdown-toggle nav-item-iconic" data-toggle="dropdown" id="dropdownMenu2">...</a>                                                                                                                                                     
       (Session info: chrome=57.0.2987.133)                                                                                                                         
       (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.10.8-200.fc25.x86_64 x86_64)                              
         at WebDriverError (/home/jludvice/devel/redhat/ipaas/ipaas-ui/node_modules/selenium-webdriver/lib/error.js:27:5)                                           
         at Object.checkLegacyResponse (/home/jludvice/devel/redhat/ipaas/ipaas-ui/node_modules/selenium-webdriver/lib/error.js:505:15)                             
         at parseHttpResponse (/home/jludvice/devel/redhat/ipaas/ipaas-ui/node_modules/selenium-webdriver/lib/http.js:509:13)                                       
         at doSend.then.response (/home/jludvice/devel/redhat/ipaas/ipaas-ui/node_modules/selenium-webdriver/lib/http.js:440:13)                                    
         at process._tickCallback (internal/process/next_tick.js:109:7)
     From: Task: WebElement.click()
```
![create](https://cloud.githubusercontent.com/assets/8707241/24860450/f66643be-1df4-11e7-84a9-832590d33eb3.png)

Using higher resolution works fine because Next button is visible.
Need to find a way to first scroll / focus the element and then click.

**Comment by jludvice** [comment]
Resolved by #476
