### ISSUE TITLE
Data Mapper step fails to load

### ISSUE THREAD

**Issue by kcbabo** [redhat-ipaas/ipaas-ui#417]
Running a build from tonight and noticed that the Data Mapping step is broken.  Clicking on it opens up the data mapping UI page with a background, but is just says "Loading ..." forever.  This is different from before as it doesn't resolve when trying to load the mapping multiple times.  I checked the data-mapper pod log and see:
```
2017-04-12 02:38:49.759 ERROR 1 --- [ XNIO-3 task-14] c.m.atlas.java.service.v2.JavaService    : Error inspecting class with classpath: ClassName and Classpath must be specified

com.mediadriver.atlas.java.inspect.v2.InspectionException: ClassName and Classpath must be specified
```

Full stack trace below ...
```
Picked up JAVA_TOOL_OPTIONS: -Duser.home=/deployments -Duser.name=jboss
mvn: [INFO] Scanning for projects...
mvn: [WARNING] 
mvn: [WARNING] Some problems were encountered while building the effective model for com.redhat.ipaas.integrations:project:jar:0.1-SNAPSHOT
mvn: [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: com.redhat.ipaas:trade-insight-buy-connector:jar -> duplicate declaration of version 0.3.5 @ line 103, column 17
mvn: [WARNING] 
mvn: [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
mvn: [WARNING] 
mvn: [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
mvn: [WARNING] 
mvn: [INFO]                                                                         
mvn: [INFO] ------------------------------------------------------------------------
mvn: [INFO] Building iPaaS Integrations :: 0.1-SNAPSHOT
mvn: [INFO] ------------------------------------------------------------------------
mvn: [INFO] 
mvn: [INFO] --- maven-dependency-plugin:3.0.0:build-classpath (default-cli) @ project ---
mvn: [INFO] Dependencies classpath:
mvn: /deployments/.m2/repository/org/springframework/spring-web/4.3.7.RELEASE/spring-web-4.3.7.RELEASE.jar:/deployments/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.8.0/jackson-annotations-2.8.0.jar:/deployments/.m2/repository/com/sun/xml/bind/jaxb-core/2.2.11/jaxb-core-2.2.11.jar:/deployments/.m2/repository/com/squareup/okio/okio/1.11.0/okio-1.11.0.jar:/deployments/.m2/repository/org/apache/camel/camel-catalog/2.19.0.fuse-000035/camel-catalog-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/apache/camel/camel-http4/2.19.0.fuse-000035/camel-http4-2.19.0.fuse-000035.jar:/deployments/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.6.0/logging-interceptor-3.6.0.jar:/deployments/.m2/repository/org/apache/camel/camel-servlet-starter/2.19.0.fuse-000035/camel-servlet-starter-2.19.0.fuse-000035.jar:/deployments/.m2/repository/io/fabric8/spring-cloud-kubernetes-core/0.1.5/spring-cloud-kubernetes-core-0.1.5.jar:/deployments/.m2/repository/org/springframework/spring-core/4.3.7.RELEASE/spring-core-4.3.7.RELEASE.jar:/deployments/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.8.7/jackson-databind-2.8.7.jar:/deployments/.m2/repository/org/slf4j/jul-to-slf4j/1.7.24/jul-to-slf4j-1.7.24.jar:/deployments/.m2/repository/org/springframework/spring-expression/4.3.7.RELEASE/spring-expression-4.3.7.RELEASE.jar:/deployments/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar:/deployments/.m2/repository/io/undertow/undertow-core/1.4.11.Final/undertow-core-1.4.11.Final.jar:/deployments/.m2/repository/org/apache/camel/camel-http4-starter/2.19.0.fuse-000035/camel-http4-starter-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/apache/camel/camel-servlet/2.19.0.fuse-000035/camel-servlet-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/apache/camel/camel-jackson-starter/2.19.0.fuse-000035/camel-jackson-starter-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/apache/camel/camel-core/2.19.0.fuse-000035/camel-core-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/1.5.2.RELEASE/spring-boot-starter-tomcat-1.5.2.RELEASE.jar:/deployments/.m2/repository/org/springframework/spring-beans/4.3.7.RELEASE/spring-beans-4.3.7.RELEASE.jar:/deployments/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.8.7/jackson-core-2.8.7.jar:/deployments/.m2/repository/io/fabric8/funktion/funktion-model/1.1.55/funktion-model-1.1.55.jar:/deployments/.m2/repository/io/fabric8/funktion/funktion-runtime/1.1.55/funktion-runtime-1.1.55.jar:/deployments/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar:/deployments/.m2/repository/com/jayway/jsonpath/json-path/2.2.0/json-path-2.2.0.jar:/deployments/.m2/repository/org/glassfish/javax.el/3.0.0/javax.el-3.0.0.jar:/deployments/.m2/repository/org/slf4j/log4j-over-slf4j/1.7.24/log4j-over-slf4j-1.7.24.jar:/deployments/.m2/repository/org/springframework/boot/spring-boot-starter-actuator/1.5.2.RELEASE/spring-boot-starter-actuator-1.5.2.RELEASE.jar:/deployments/.m2/repository/org/springframework/spring-aop/4.3.7.RELEASE/spring-aop-4.3.7.RELEASE.jar:/deployments/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/deployments/.m2/repository/org/apache/camel/camel-spring-boot-starter/2.19.0.fuse-000035/camel-spring-boot-starter-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/apache/camel/camel-connector/2.19.0.fuse-000035/camel-connector-2.19.0.fuse-000035.jar:/deployments/.m2/repository/com/squareup/okhttp3/okhttp/3.6.0/okhttp-3.6.0.jar:/deployments/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/deployments/.m2/repository/org/apache/camel/camel-http-common/2.19.0.fuse-000035/camel-http-common-2.19.0.fuse-000035.jar:/deployments/.m2/repository/io/undertow/undertow-servlet/1.4.11.Final/undertow-servlet-1.4.11.Final.jar:/deployments/.m2/repository/org/jboss/spec/javax/annotation/jboss-annotations-api_1.2_spec/1.0.0.Final/jboss-annotations-api_1.2_spec-1.0.0.Final.jar:/deployments/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar:/deployments/.m2/repository/org/jboss/xnio/xnio-nio/3.3.6.Final/xnio-nio-3.3.6.Final.jar:/deployments/.m2/repository/org/apache/httpcomponents/httpclient/4.5.3/httpclient-4.5.3.jar:/deployments/.m2/repository/org/apache/camel/camel-core-starter/2.19.0.fuse-000035/camel-core-starter-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar:/deployments/.m2/repository/org/springframework/boot/spring-boot-starter-logging/1.5.2.RELEASE/spring-boot-starter-logging-1.5.2.RELEASE.jar:/deployments/.m2/repository/org/springframework/boot/spring-boot-starter/1.5.2.RELEASE/spring-boot-starter-1.5.2.RELEASE.jar:/deployments/.m2/repository/org/springframework/security/spring-security-crypto/4.2.2.RELEASE/spring-security-crypto-4.2.2.RELEASE.jar:/deployments/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.8.7/jackson-dataformat-yaml-2.8.7.jar:/deployments/.m2/repository/org/apache/camel/camel-jsonpath/2.19.0.fuse-000035/camel-jsonpath-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/springframework/boot/spring-boot-configuration-processor/1.5.2.RELEASE/spring-boot-configuration-processor-1.5.2.RELEASE.jar:/deployments/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.24/jcl-over-slf4j-1.7.24.jar:/deployments/.m2/repository/org/slf4j/slf4j-api/1.7.24/slf4j-api-1.7.24.jar:/deployments/.m2/repository/org/apache/camel/apt/2.19.0.fuse-000035/apt-2.19.0.fuse-000035.jar:/deployments/.m2/repository/ch/qos/logback/logback-core/1.1.11/logback-core-1.1.11.jar:/deployments/.m2/repository/org/apache/camel/camel-spring-boot/2.19.0.fuse-000035/camel-spring-boot-2.19.0.fuse-000035.jar:/deployments/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar:/deployments/.m2/repository/org/apache/camel/spi-annotations/2.19.0.fuse-000035/spi-annotations-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/springframework/boot/spring-boot-actuator/1.5.2.RELEASE/spring-boot-actuator-1.5.2.RELEASE.jar:/deployments/.m2/repository/org/springframework/boot/spring-boot-starter-web/1.5.2.RELEASE/spring-boot-starter-web-1.5.2.RELEASE.jar:/deployments/.m2/repository/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.8.7/jackson-module-jaxb-annotations-2.8.7.jar:/deployments/.m2/repository/com/github/mifmif/generex/1.0.1/generex-1.0.1.jar:/deployments/.m2/repository/org/springframework/boot/spring-boot-starter-undertow/1.5.2.RELEASE/spring-boot-starter-undertow-1.5.2.RELEASE.jar:/deployments/.m2/repository/org/hibernate/hibernate-validator/5.3.4.Final/hibernate-validator-5.3.4.Final.jar:/deployments/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/deployments/.m2/repository/io/fabric8/kubernetes-model/1.0.67/kubernetes-model-1.0.67.jar:/deployments/.m2/repository/io/fabric8/zjsonpatch/0.3.0/zjsonpatch-0.3.0.jar:/deployments/.m2/repository/org/springframework/spring-tx/4.3.7.RELEASE/spring-tx-4.3.7.RELEASE.jar:/deployments/.m2/repository/org/apache/camel/camel-jsonpath-starter/2.19.0.fuse-000035/camel-jsonpath-starter-2.19.0.fuse-000035.jar:/deployments/.m2/repository/com/redhat/ipaas/trade-insight-buy-connector/0.3.5/trade-insight-buy-connector-0.3.5.jar:/deployments/.m2/repository/org/apache/camel/camel-spring/2.19.0.fuse-000035/camel-spring-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/1.5.2.RELEASE/spring-boot-autoconfigure-1.5.2.RELEASE.jar:/deployments/.m2/repository/com/github/ben-manes/caffeine/caffeine/2.3.5/caffeine-2.3.5.jar:/deployments/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/deployments/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.11/jaxb-impl-2.2.11.jar:/deployments/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/8.5.11/tomcat-embed-websocket-8.5.11.jar:/deployments/.m2/repository/org/apache/camel/camel-jackson/2.19.0.fuse-000035/camel-jackson-2.19.0.fuse-000035.jar:/deployments/.m2/repository/org/jboss/spec/javax/websocket/jboss-websocket-api_1.1_spec/1.1.0.Final/jboss-websocket-api_1.1_spec-1.1.0.Final.jar:/deployments/.m2/repository/net/minidev/json-smart/2.2.1/json-smart-2.2.1.jar:/deployments/.m2/repository/org/springframework/boot/spring-boot/1.5.2.RELEASE/spring-boot-1.5.2.RELEASE.jar:/deployments/.m2/repository/net/minidev/accessors-smart/1.1/accessors-smart-1.1.jar:/deployments/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/8.5.11/tomcat-embed-core-8.5.11.jar:/deployments/.m2/repository/org/springframework/spring-context/4.3.7.RELEASE/spring-context-4.3.7.RELEASE.jar:/deployments/.m2/repository/org/springframework/cloud/spring-cloud-context/1.1.7.RELEASE/spring-cloud-context-1.1.7.RELEASE.jar:/deployments/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar:/deployments/.m2/repository/com/fasterxml/classmate/1.3.3/classmate-1.3.3.jar:/deployments/.m2/repository/io/undertow/undertow-websockets-jsr/1.4.11.Final/undertow-websockets-jsr-1.4.11.Final.jar:/deployments/.m2/repository/io/fabric8/kubernetes-client/2.2.0/kubernetes-client-2.2.0.jar:/deployments/.m2/repository/ch/qos/logback/logback-classic/1.1.11/logback-classic-1.1.11.jar:/deployments/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/8.5.11/tomcat-embed-el-8.5.11.jar:/deployments/.m2/repository/org/jboss/xnio/xnio-api/3.3.6.Final/xnio-api-3.3.6.Final.jar:/deployments/.m2/repository/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar
mvn: [INFO] ------------------------------------------------------------------------
mvn: [INFO] BUILD SUCCESS
mvn: [INFO] ------------------------------------------------------------------------
mvn: [INFO] Total time: 2.506 s
mvn: [INFO] Finished at: 2017-04-12T02:38:49+00:00
mvn: [INFO] Final Memory: 32M/314M
mvn: [INFO] ------------------------------------------------------------------------
2017-04-12 02:38:49.759 ERROR 1 --- [ XNIO-3 task-14] c.m.atlas.java.service.v2.JavaService    : Error inspecting class with classpath: ClassName and Classpath must be specified

com.mediadriver.atlas.java.inspect.v2.InspectionException: ClassName and Classpath must be specified
	at com.mediadriver.atlas.java.inspect.v2.ClassInspectionService.inspectClass(ClassInspectionService.java:174) ~[atlas.java.inspect-1.10.0-SNAPSHOT.jar!/:1.10.0-SNAPSHOT]
	at com.mediadriver.atlas.java.service.v2.JavaService.inspectClass(JavaService.java:155) ~[atlas.java.service-1.10.0-SNAPSHOT.jar!/:1.10.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) [resteasy-jaxrs-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294) [resteasy-jaxrs-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248) [resteasy-jaxrs-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235) [resteasy-jaxrs-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398) [resteasy-jaxrs-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205) [resteasy-jaxrs-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221) [resteasy-jaxrs-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [resteasy-jaxrs-3.1.0.Final.jar!/:3.1.0.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [resteasy-jaxrs-3.1.0.Final.jar!/:3.1.0.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:108) [spring-boot-actuator-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) [spring-boot-actuator-1.5.2.RELEASE.jar!/:1.5.2.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) [undertow-servlet-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211) [undertow-core-1.4.11.Final.jar!/:1.4.11.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809) [undertow-core-1.4.11.Final.jar!/:1.4.11.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by gashcrumb** [comment]
News to me, @chirino any update to the backend stuff that might affect this?

**Comment by gashcrumb** [comment]
Seems BTW like there's a disparity between staging and the current templates maybe?  As on staging the data mapper still seems to load fine.

**Comment by kcbabo** [comment]
Just tried the latest build and do not see this issue.
