### ISSUE TITLE
e2e tests won't run

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-ui#52]
Been looking into this issue this afternoon:

```
~/Work/src/hawtio-ipaas
] npm run e2e

> hawtio-ipaas@1.0.0 pree2e /home/gashcrumb/Work/src/hawtio-ipaas
> npm run webdriver:update -- --standalone


> hawtio-ipaas@1.0.0 webdriver:update /home/gashcrumb/Work/src/hawtio-ipaas
> npm run webdriver-manager update "--standalone"


> hawtio-ipaas@1.0.0 webdriver-manager /home/gashcrumb/Work/src/hawtio-ipaas
> webdriver-manager "update"

selenium standalone is up to date.
chromedriver is up to date.

> hawtio-ipaas@1.0.0 e2e /home/gashcrumb/Work/src/hawtio-ipaas
> npm run protractor


> hawtio-ipaas@1.0.0 protractor /home/gashcrumb/Work/src/hawtio-ipaas
> protractor

[15:24:07] I/direct - Using ChromeDriver directly...
[15:24:07] I/launcher - Running 1 instances of WebDriver

/home/gashcrumb/Work/src/hawtio-ipaas/node_modules/selenium-webdriver/http/index.js:365
      onError(new Error(message));
              ^
Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:40954
    at ClientRequest.<anonymous> (/home/gashcrumb/Work/src/hawtio-ipaas/node_modules/selenium-webdriver/http/index.js:365:15)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From: Task: WebDriver.createSession()
    at acquireSession (/home/gashcrumb/Work/src/hawtio-ipaas/node_modules/selenium-webdriver/lib/webdriver.js:62:22)
    at Function.createSession (/home/gashcrumb/Work/src/hawtio-ipaas/node_modules/selenium-webdriver/lib/webdriver.js:295:12)
    at Driver (/home/gashcrumb/Work/src/hawtio-ipaas/node_modules/selenium-webdriver/chrome.js:778:38)
    at Direct.getNewDriver (/home/gashcrumb/Work/src/hawtio-ipaas/node_modules/protractor/built/driverProviders/direct.js:65:26)
    at Runner.createBrowser (/home/gashcrumb/Work/src/hawtio-ipaas/node_modules/protractor/built/runner.js:182:43)
    at /home/gashcrumb/Work/src/hawtio-ipaas/node_modules/protractor/built/runner.js:255:30
    at _fulfilled (/home/gashcrumb/Work/src/hawtio-ipaas/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/gashcrumb/Work/src/hawtio-ipaas/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/gashcrumb/Work/src/hawtio-ipaas/node_modules/q/q.js:796:13)
    at /home/gashcrumb/Work/src/hawtio-ipaas/node_modules/q/q.js:556:49
[15:24:08] E/launcher - Process exited with error code 1
```

**Comment by gashcrumb** [comment]
@kahboom btw, have you seen this by any chance?

**Comment by kahboom** [comment]
@gashcrumb Nope, I'll take a look today or tomorrow as I've been excited to get these working. :)

**Comment by kahboom** [comment]
For personal reference:

```
> ipaas-client-cli@0.0.0 e2e /Users/kahboom/Projects/ipaas-client
> protractor

(node:12671) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[12:03:07] I/direct - Using ChromeDriver directly...
[12:03:07] I/launcher - Running 1 instances of WebDriver
[12:03:08] E/launcher - Error: TypeError: SpecReporter is not a constructor
    at onPrepare (/Users/kahboom/Projects/ipaas-client/protractor.conf.js:30:34)
    at q_1.Promise (/Users/kahboom/Projects/ipaas-client/node_modules/protractor/lib/util.ts:47:39)
    at Function.promise (/Users/kahboom/Projects/ipaas-client/node_modules/q/q.js:682:9)
    at Object.runFilenameOrFn_ (/Users/kahboom/Projects/ipaas-client/node_modules/protractor/lib/util.ts:38:10)
    at plugins_.onPrepare.then (/Users/kahboom/Projects/ipaas-client/node_modules/protractor/lib/runner.ts:85:21)
    at _fulfilled (/Users/kahboom/Projects/ipaas-client/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/kahboom/Projects/ipaas-client/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/kahboom/Projects/ipaas-client/node_modules/q/q.js:796:13)
    at /Users/kahboom/Projects/ipaas-client/node_modules/q/q.js:556:49
    at runSingle (/Users/kahboom/Projects/ipaas-client/node_modules/q/q.js:137:13)
[12:03:08] E/launcher - Process exited with error code 100

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.2.1/bin/node" "/usr/local/bin/npm" "run" "e2e"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ipaas-client-cli@0.0.0 e2e: `protractor`
npm ERR! Exit status 100
npm ERR! 
npm ERR! Failed at the ipaas-client-cli@0.0.0 e2e script 'protractor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ipaas-client-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ipaas-client-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ipaas-client-cli
npm ERR! There is likely additional logging output above.
```

**Comment by jludvice** [comment]
Hello @gashcrumb @kahboom 

Does #152 fix this issue?

**Comment by gashcrumb** [comment]
@jludvice yeah, seems to!  though I hit the same problem you mention in the PR with the github authentication...

**Comment by jludvice** [comment]
Just for the reference, jasmine spec reporter was removed as part of switching to cucumber.js  in #190 
It should be possible to mix jasmine and cucumber together if we really need to.

**Comment by kahboom** [comment]
Ty @jludvice . Would you mind updating the README? If not I can do that in my next PR.

**Comment by jludvice** [comment]
@kahboom I tried to draft test readme in `e2e/Readme.md` in [my branch](https://github.com/jludvice/ipaas-ui/tree/cucumber/e2e)
I could update main readme when we finally merge e2e tests to master if that's ok.

**Comment by kahboom** [comment]
@jludvice - Sure no problem, just remember to keep rebasing with master so you don't diverge too much and have to deal with a ton of merge conflicts.
