### ISSUE TITLE
Error showing up in npm test, Can't resolve '../common/title' 

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-ui#68]
Tests don't fail due to this, but it shows up when you run `npm test`:

```
ERROR in ./src/app/+dashboard/dashboard.spec.ts
Module not found: Error: Can't resolve '../common/title' in '/home/gashcrumb/Work/src/ipaas-client/src/app/+dashboard'
 @ ./src/app/+dashboard/dashboard.spec.ts 1:0-37:2
 @ ./src \.spec\.ts$
 @ ./config/spec-bundle.js
```

And also shows up in the js console:

```
Chrome 54.0.2840 (Linux 0.0.0) ERROR: 'Failed to load module: ', './app/+dashboard/dashboard.spec.ts', ' error: ', 'Cannot find module "../common/title"'
```

**Comment by kahboom** [comment]
After resolving that issue, tests for the Dashboard component still fail. Pretty sure I know why, will look into this in the morning.

```
SUMMARY:
✔ 16 tests completed
✖ 2 tests failed

FAILED TESTS:
  Dashboard
    ✖ should have default data
      Chrome 54.0.2840 (Mac OS X 10.12.1)
    Error: No provider for Router!
        at NoProviderError.BaseError [as constructor] (webpack:///~/@angular/core/src/facade/errors.js:24:0 <- config/spec-bundle.js:7629:34)
        at NoProviderError.AbstractProviderError [as constructor] (webpack:///~/@angular/core/src/di/reflective_errors.js:42:0 <- config/spec-bundle.js:38007:16)
        at new NoProviderError (webpack:///~/@angular/core/src/di/reflective_errors.js:73:0 <- config/spec-bundle.js:38038:16)
        at ReflectiveInjector_._throwOrNull (webpack:///~/@angular/core/src/di/reflective_injector.js:761:0 <- config/spec-bundle.js:61186:19)
        at ReflectiveInjector_._getByKeyDefault (webpack:///~/@angular/core/src/di/reflective_injector.js:789:0 <- config/spec-bundle.js:61214:25)
        at ReflectiveInjector_._getByKey (webpack:///~/@angular/core/src/di/reflective_injector.js:752:0 <- config/spec-bundle.js:61177:25)
        at ReflectiveInjector_.get (webpack:///~/@angular/core/src/di/reflective_injector.js:561:0 <- config/spec-bundle.js:60986:21)
        at DynamicTestModuleInjector.createInternal (DynamicTestModule.ngfactory.js:156:56)
        at DynamicTestModuleInjector.NgModuleInjector.create (webpack:///~/@angular/core/src/linker/ng_module_factory.js:88:53 <- config/spec-bundle.js:38928:76)
        at NgModuleFactory.create (webpack:///~/@angular/core/src/linker/ng_module_factory.js:73:0 <- config/spec-bundle.js:38913:18)
        at TestBed._initIfNeeded (webpack:///~/@angular/core/bundles/core-testing.umd.js:1072:0 <- config/spec-bundle.js:5366:68)
        at TestBed.execute (webpack:///~/@angular/core/bundles/core-testing.umd.js:1119:0 <- config/spec-bundle.js:5413:18)
        at Object.<anonymous> (webpack:///~/@angular/core/bundles/core-testing.umd.js:1211:32 <- config/spec-bundle.js:5505:49)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:192:0 <- config/spec-bundle.js:51242:28)
        at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:60:0 <- config/spec-bundle.js:50969:43)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:191:0 <- config/spec-bundle.js:51241:34)
        at Zone.run (webpack:///~/zone.js/dist/zone.js:85:0 <- config/spec-bundle.js:51135:43)
        at Object.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:78:27 <- config/spec-bundle.js:50734:50)
        at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:106:0 <- config/spec-bundle.js:50762:42)
        at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:106:0 <- config/spec-bundle.js:50762:42)
        at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:225:0 <- config/spec-bundle.js:51275:37)
        at Zone.runTask (webpack:///~/zone.js/dist/zone.js:125:0 <- config/spec-bundle.js:51175:47)
        at drainMicroTaskQueue (webpack:///~/zone.js/dist/zone.js:357:0 <- config/spec-bundle.js:51407:35)

    ✖ should log ngOnInit
      Chrome 54.0.2840 (Mac OS X 10.12.1)
    Error: No provider for Router!
        at NoProviderError.BaseError [as constructor] (webpack:///~/@angular/core/src/facade/errors.js:24:0 <- config/spec-bundle.js:7629:34)
        at NoProviderError.AbstractProviderError [as constructor] (webpack:///~/@angular/core/src/di/reflective_errors.js:42:0 <- config/spec-bundle.js:38007:16)
        at new NoProviderError (webpack:///~/@angular/core/src/di/reflective_errors.js:73:0 <- config/spec-bundle.js:38038:16)
        at ReflectiveInjector_._throwOrNull (webpack:///~/@angular/core/src/di/reflective_injector.js:761:0 <- config/spec-bundle.js:61186:19)
        at ReflectiveInjector_._getByKeyDefault (webpack:///~/@angular/core/src/di/reflective_injector.js:789:0 <- config/spec-bundle.js:61214:25)
        at ReflectiveInjector_._getByKey (webpack:///~/@angular/core/src/di/reflective_injector.js:752:0 <- config/spec-bundle.js:61177:25)
        at ReflectiveInjector_.get (webpack:///~/@angular/core/src/di/reflective_injector.js:561:0 <- config/spec-bundle.js:60986:21)
        at DynamicTestModuleInjector.createInternal (DynamicTestModule.ngfactory.js:156:56)
        at DynamicTestModuleInjector.NgModuleInjector.create (webpack:///~/@angular/core/src/linker/ng_module_factory.js:88:53 <- config/spec-bundle.js:38928:76)
        at NgModuleFactory.create (webpack:///~/@angular/core/src/linker/ng_module_factory.js:73:0 <- config/spec-bundle.js:38913:18)
        at TestBed._initIfNeeded (webpack:///~/@angular/core/bundles/core-testing.umd.js:1072:0 <- config/spec-bundle.js:5366:68)
        at TestBed.execute (webpack:///~/@angular/core/bundles/core-testing.umd.js:1119:0 <- config/spec-bundle.js:5413:18)
        at Object.<anonymous> (webpack:///~/@angular/core/bundles/core-testing.umd.js:1211:32 <- config/spec-bundle.js:5505:49)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:192:0 <- config/spec-bundle.js:51242:28)
        at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:60:0 <- config/spec-bundle.js:50969:43)
        at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:191:0 <- config/spec-bundle.js:51241:34)
        at Zone.run (webpack:///~/zone.js/dist/zone.js:85:0 <- config/spec-bundle.js:51135:43)
        at Object.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:78:27 <- config/spec-bundle.js:50734:50)
        at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:106:0 <- config/spec-bundle.js:50762:42)
        at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:225:0 <- config/spec-bundle.js:51275:37)
        at Zone.runTask (webpack:///~/zone.js/dist/zone.js:125:0 <- config/spec-bundle.js:51175:47)
        at drainMicroTaskQueue (webpack:///~/zone.js/dist/zone.js:357:0 <- config/spec-bundle.js:51407:35)

```
